name = "telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
TELEGRAM_BOT_TOKEN = "ТВОЙ_ТОКЕН_БОТА"

[build]
command = "npm run build"

[[assets]]
directory = "./scripts"
binding = "SCRIPTS"
